server:
  port: 18081

doge:
  registry: zookeeper
  zookeeper:
    host: #must
    port: 2181
    connection-timeout: 60000
    session-timeout: 60000
    retry-sleep-time: 5000
    max-retries: 5
  server:
    port: 20002 #must


spring:
  redis:  # must if use redis
    database: 0
    host: 
    port: 6379
    timeout: 10s
    password: 
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1m


