

doge:
  zookeeper:
    host: 
    port: 2181
    connection-timeout: 60000
    session-timeout: 60000
    retry-sleep-time: 5000
    max-retries: 5
  monitor:
    enable: true
  remote:
    monitor-host: 127.0.0.1
    monitor-port: 18888
server:
  port: 8080